# Genetic algorithm parameters
POPULATION_SIZE = 10000
ELITE_PERCENTAGE = 0.01
MAX_GENERATIONS = 75

INITIAL_MUTATION_RATE = 0.06
MIN_MUTATION_RATE = 0.01
MAX_MUTATION_RATE = 0.40
MEDIAN_FITNESS_UPPER_BOUND_RATIO = 0.70
MEDIAN_FITNESS_LOWER_BOUND_RATIO = 0.50
MUTATION_RATE_ADJUSTMENT_STEP = 0.005
